### PR TITLE
switch to cmake build system

### PR DESCRIPTION
**Pull request by tedbrandston**

### CODE REVIEW

**Comment by nicholasbishop** [comment]
<3

**Comment by tedbrandston** [comment]
:iamdying: :itneverends: :crying_person: :fetal_position:

**Comment by nicholasbishop** [comment]
:hugz:

**Comment by pnardini** [comment]
Ted, you should drop this CMake nonsense and start using Gradle.

**Comment by nicholasbishop** [comment]
Nah just use the Google build system https://code.google.com/p/gyp/
No sorry I meant use the Google build system https://code.google.com/p/chromium/wiki/gn
Damn actually I meant use the Google build system http://bazel.io/

:put_litter_in_its_place:

**Comment by pnardini** [comment]
How about the Google build system? https://code.google.com/p/chromium/wiki/NinjaBuild

**Comment by benfeltz** [comment]
Guys, it is 2015, we need to embrace the now. We are moving to FAke http://fsharp.github.io/FAKE/

**Comment by tedbrandston** [comment]
I've actually started working on a cross-platform version of tup http://gittup.org/tup/

The graphs there are really convincing, tup is definitely going to be the future of build systems. And once I've got it running on windows I can write a CMake generator for Tupfiles!

tup# cmake# yolo#

**Comment by benfeltz** [comment]
http://bud.urbas.si/About

Super fast, highly customisable, and modern

**Comment by tedbrandston** [comment]
It's SCons for C#?

**Comment by pnardini** [comment]
"See the difference? The arrows go up. This makes it very fast." - greatest argument ever for using a software tool.  Thanks Ted, that made my day.

**Pull request merged**
